name: reminders
description: Read, Edit, Create and Delete Apple Reminders
version: 2.0.0
homepage:  # forked from https://github.com/berkobob/reminders

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: RemindersPlugin
      macos:
        pluginClass: RemindersPlugin
